### GET account
GET localhost:3000/account

###

### GET all accounts
GET localhost:3000/account

###

### POST create account
POST localhost:3000/account
Content-Type: application/json

{
  "firstName" : "Rita",
  "lastName": "Correia"
}

###

### GET account by id
GET localhost:3000/account/1

###
