### GET all accounts
GET localhost:3000/account

### POST create account
POST localhost:3000/account
Content-Type: application/json

{
  "firstName" : "Rita",
  "lastName": "Correia2"
}

### GET account by id
GET localhost:3000/account/5

### DELETE account by id
DELETE localhost:3000/account/5


### POST transfer
POST localhost:3000/transfer
Content-Type: application/json

{
  "toAccount": 234,
  "amount": 40
}