### GET all accounts
GET localhost:3000/account

### POST create account
POST localhost:3000/account
Content-Type: application/json

{
  "firstName" : "Rita",
  "lastName": "Correia2"
}

### GET account by id
GET localhost:3000/account/8
x-jwt-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjo2ODU2MjksImV4cGlyZXNBdCI6MTUwMDB9.F17T3MZpS9I3KDSp0_Wh0WVFEB1iqBh7bQXB_hcM-yU


### DELETE account by id
DELETE localhost:3000/account/5


### POST transfer
POST localhost:3000/transfer
Content-Type: application/json

{
  "toAccount": 234,
  "amount": 40
}